<a href="https://colab.research.google.com/github/izzanurafifah/website_scraping_qs_world_university_rankings_2024/blob/main/qs_world_university_rankings_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
base_url = "https://www.topuniversities.com/rankings/endpoint?nid=3897789&page={}&items_per_page=100&tab="

total_pages = 15
all_universities = []

for page_number in range(total_pages):
  url = base_url.format(page_number)
  page = requests.get(url)
  json_data = page.json()
  json_data = json_data['score_nodes']
  all_universities.extend(json_data)

In [ ]:
print(all_universities)

In [4]:
def get_title(titles):
  title_list = []
  for title in titles:
    title = title['title']
    title_list.append(title)
  return title_list

def get_region(regions):
  region_list = []
  for region in regions:
    region = region['region']
    region_list.append(region)
  return region_list

def get_country(countries):
  country_list = []
  for country in countries:
    country = country['country']
    country_list.append(country)
  return country_list

def get_city(cities):
  city_list = []
  for city in cities:
    city = city['city']
    city_list.append(city)
  return city_list

def get_overallscore(overallscores):
  overallscore_list = []
  for overallscore in overallscores:
    overallscore = overallscore['overall_score']
    overallscore_list.append(overallscore)
  return overallscore_list

def get_rank(ranks):
  rank_list = []
  for rank in ranks:
    rank = rank['rank']
    rank_list.append(rank)
  return rank_list

In [5]:
titles = get_title(all_universities)
regions = get_region(all_universities)
countries = get_country(all_universities)
cities = get_city(all_universities)
overall_scores = get_overallscore(all_universities)
ranks = get_rank(all_universities)

In [6]:
table = list(zip(ranks, titles, overall_scores, cities, countries, regions))

In [8]:
import pandas as pd

header = ['Rank', 'University', 'Overall Score', 'City', 'Country', 'Region']

df = pd.DataFrame(table, columns=header)

df

,Rank,University,Overall Score,City,Country,Region
0,1,Massachusetts Institute of Technology (MIT),100,Cambridge,United States,North America
1,2,University of Cambridge,99.2,Cambridge,United Kingdom,Europe
2,3,University of Oxford,98.9,Oxford,United Kingdom,Europe
3,4,Harvard University,98.3,Cambridge,United States,North America
4,5,Stanford University,98.1,Stanford,United States,North America
...,...,...,...,...,...,...
1493,1494,University of Oradea,n/a,Oradea,Romania,Europe
1494,1495,University of Stavanger,n/a,Stavanger,Norway,Europe
1495,1496,Universit√© Paris 13 Nord,n/a,Villetaneuse,France,Europe
1496,1497,Western Washington University,n/a,Bellingham,United States,North America
1497,1498,Zurich University of Applied Sciences (ZHAW),n/a,Winterthur,Switzerland,Europe